apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels: 
    name: result-service
    app: demo-voting-app  
spec:
  type: NodePort
  ports: 
    - targetPort: 80
      port: 80
      nodePort: 30005
  selector:
    name: result-app-pod
    app: demo-voting-app
